In [10]:
import numpy as np
import tensorflow as tf
import matplotlib.pyplot as plt
import sympy as sp


In [35]:
x1 = sp.Symbol('x_1')
x2 = sp.Symbol('x_2')


sin(2x − y) − 1.2x = 0.4;
0.8x2 + 1.5y2 = 1 .

In [76]:
F = sp.Matrix([sp.sin(2*x1-x2) - 1.2*x1 - 0.4, 0.8*x1**2 + 1.5*x2**2-1])
F

Matrix([
[-1.2*x_1 + sin(2*x_1 - x_2) - 0.4],
[      0.8*x_1**2 + 1.5*x_2**2 - 1]])

In [79]:
sp.lambdify([x1, x2], F)(1,2).

(2, 1)

In [68]:
dF_dx = F.jacobian([x1,x2])
sp.lambdify([x1, x2], dF_dx, 'numpy')(*np.array([1.0,2.3]))

array([[ 0.71067298, -0.95533649],
       [ 1.6       ,  6.9       ]])

In [111]:
def newton_solve(F: sp.Matrix, x0: np.array, tol, symbol_x, history_save = True):
    '''
    System of nonlinear equations solver (Newton method)
    
    Args:
        F (sp.Matrix): System of nonlinear equations F(x)=0
        x0 (np.array): first point in the iteration
        tol (float): tolerance
        symbol_x (list): list of symbol variables
    '''    
#     Create history array
    if history_save:
        history = [x0]
#     Define numerical F
    numerical_F = sp.lambdify(symbol_x, F)
#     Define symbol jacobian and numerical jacobian
    dF_dx = F.jacobian(symbol_x)
    numerical_dF_dx = sp.lambdify(symbol_x, dF_dx, 'numpy')
#     Solve the system of linear equations dF_dx(xk) *dxk = -F(xk) in a loop
    k=0
    while True:
        dx1 = np.linalg.solve(numerical_dF_dx(*x0), -numerical_F(*x0))
        dx1 = np.squeeze(dx1)
#         x1 = np.sum([x0, dx1], axis = 0)
        x1 = x0+dx1
#     Add value to history list
        if history_save:
            history.append(x1)
        if np.linalg.norm(x1 - x0)<=tol:
            print(f'k={k}: norm ||x_k+1 - x_k||<={tol}')
            return x1 if not history_save else x1, history
        k+=1
        x0 = x1

In [112]:
newton_solve(F, np.array([0.4, -0.75]), 0.0001, [x1, x2])

k=3: norm ||x_k+1 - x_k||<=0.0001


(array([ 0.49123795, -0.7334613 ]),
 [array([ 0.4 , -0.75]),
  array([ 0.5031025 , -0.73322862]),
  array([ 0.49141694, -0.73344703]),
  array([ 0.49123799, -0.7334613 ]),
  array([ 0.49123795, -0.7334613 ])])